-- Bronze raw tables with real source columns (from Week 2 schema discovery).
-- Apply AFTER 00_schemas.sql and 01_platform_tables.sql.

CREATE TABLE IF NOT EXISTS bronze.raw_products (
  ieprod_iden    NUMERIC,
  iecate_codc    NUMERIC,
  iecate_nomc    TEXT,
  ieprod_codp    TEXT,
  ieprod_desp    TEXT,
  iemarc_iden    NUMERIC,
  iemarc_nomb    TEXT,
  ieprod_obse    TEXT,
  ieprod_pcos    DOUBLE PRECISION,
  ieprod_viva    TEXT,
  ieprod_pvpp    DOUBLE PRECISION,
  ieprod_pvp1    DOUBLE PRECISION,
  ieprod_pvp2    DOUBLE PRECISION,
  ieprod_pvp3    DOUBLE PRECISION,
  ieprod_pvp4    DOUBLE PRECISION,
  ieprod_cpro    DOUBLE PRECISION,
  ieprod_tipo    TEXT,
  valiva         TEXT,
  ieprod_vitv    TEXT,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (ieprod_iden)
);

-- Kardex: journal of inventory movements. No natural compound PK exposed by the view;
-- source_row_hash used as PK for deduplication (movements are immutable).
CREATE TABLE IF NOT EXISTS bronze.raw_kardex (
  ieprod_iden    NUMERIC,
  iefave_iden    NUMERIC,
  ieprod_viva    TEXT,
  ieprod_pcos    DOUBLE PRECISION,
  ieprod_cpro    DOUBLE PRECISION,
  ieprod_codp    TEXT,
  ieprod_desp    TEXT,
  ieprod_vsst    TEXT,
  iefave_femi    TIMESTAMPTZ,
  iedefv_cant    NUMERIC,
  tipo           TEXT,
  origen         NUMERIC,
  destino        NUMERIC,
  tm             TEXT,
  almacen        NUMERIC,
  fesucu_noms    TEXT,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (source_row_hash)
);

CREATE INDEX IF NOT EXISTS idx_raw_kardex_femi ON bronze.raw_kardex (iefave_femi DESC);

CREATE TABLE IF NOT EXISTS bronze.raw_stock (
  iemarc_nomb    TEXT,
  ieprod_codp    TEXT,
  ieprod_desp    TEXT,
  ieprod_pcos    DOUBLE PRECISION,
  ieprov_empr    TEXT,
  ieprov_nomb    TEXT,
  iestop_stok    NUMERIC,
  fesucu_noms    TEXT,
  fesucu_cods    NUMERIC,
  iecate_codc    NUMERIC,
  iecate_nomc    TEXT,
  iemarc_iden    NUMERIC,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (ieprod_codp, fesucu_cods)
);

CREATE TABLE IF NOT EXISTS bronze.raw_sales (
  feclie_codc    TEXT,
  feempl_nome    TEXT,
  feempl_code    NUMERIC,
  emple_reg      TEXT,
  emple_cod      NUMERIC,
  emple_vfac     TEXT,
  emple_vcod     NUMERIC,
  fesucu_noms    TEXT,
  fesucu_cods    NUMERIC,
  iefave_ser3    NUMERIC,
  nombre         TEXT,
  feclie_iden    NUMERIC,
  iefave_civa    DOUBLE PRECISION,
  iefave_siva    DOUBLE PRECISION,
  iefave_viva    DOUBLE PRECISION,
  iefave_dsct    DOUBLE PRECISION,
  iefave_tota    DOUBLE PRECISION,
  ceautv_trib    TEXT,
  tipo_fac       TEXT,
  iefave_femi    TIMESTAMPTZ,
  ceautv_ser1    TEXT,
  ceautv_ser2    TEXT,
  peauxi_nomb    TEXT,
  iefave_vice    NUMERIC,
  iencrv_tota    DOUBLE PRECISION,
  ret_iva        DOUBLE PRECISION,
  ret_deuda      NUMERIC,
  ret_fte        DOUBLE PRECISION,
  referidor      TEXT,
  iefave_recl    NUMERIC,
  fegru1_iden    NUMERIC,
  fegru1_nomb    TEXT,
  peprov_nomb    TEXT,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (fesucu_cods, ceautv_ser1, ceautv_ser2, iefave_ser3)
);

CREATE INDEX IF NOT EXISTS idx_raw_sales_femi ON bronze.raw_sales (iefave_femi DESC);

CREATE TABLE IF NOT EXISTS bronze.raw_sales_detail (
  iestop_stok    NUMERIC,
  iedefv_iden    NUMERIC,
  iefave_iden    NUMERIC,
  fesucu_cods    NUMERIC,
  fesucu_noms    TEXT,
  iefave_femi    TIMESTAMPTZ,
  iefave_hora    TEXT,
  iefave_ser3    NUMERIC,
  iefave_fina    TEXT,
  ceautv_naut    TEXT,
  ceautv_ser1    TEXT,
  ceautv_ser2    TEXT,
  ceautv_desc    TEXT,
  ceautv_trib    TEXT,
  iedefv_cost    DOUBLE PRECISION,
  iedefv_vuni    DOUBLE PRECISION,
  iedefv_dsct    DOUBLE PRECISION,
  iedefv_viva    DOUBLE PRECISION,
  iemedx_iden    NUMERIC,
  iemedx_nomb    TEXT,
  iedefv_cang    NUMERIC,
  iedefv_obse    TEXT,
  iedefv_reca    NUMERIC,
  ieprod_iden    NUMERIC,
  ieprod_codp    TEXT,
  ieprod_desp    TEXT,
  ieprod_viva    TEXT,
  ieprod_pcos    DOUBLE PRECISION,
  placa          TEXT,
  iecate_codc    NUMERIC,
  iecate_nomc    TEXT,
  iemarc_iden    NUMERIC,
  iemarc_nomb    TEXT,
  feclie_codc    TEXT,
  feclie_apec    TEXT,
  feclie_nomc    TEXT,
  feclie_dirc    TEXT,
  feclie_telc    TEXT,
  feclie_tcec    TEXT,
  feclie_ttrc    TEXT,
  feclie_maic    TEXT,
  feempl_nome    TEXT,
  feempl_cedu    TEXT,
  seclav_codi    NUMERIC,
  seclav_usua    TEXT,
  ieserp_iden    NUMERIC,
  ieserp_seri    TEXT,
  ieserp_moto    TEXT,
  ieserp_chas    TEXT,
  ieserp_ncae    TEXT,
  ieserp_colo    TEXT,
  ieserp_tipo    TEXT,
  ieserp_anof    TEXT,
  nc_valo        DOUBLE PRECISION,
  iva_de         DOUBLE PRECISION,
  ieserp_matr    TEXT,
  ieserp_plac    TEXT,
  ieserp_jefa    TEXT,
  ieserp_orig    TEXT,
  ieserp_tone    TEXT,
  ieserp_cili    TEXT,
  iedenp_iden    NUMERIC,
  iedenp_plan    NUMERIC,
  iedcrv_iden    NUMERIC,
  provincia      TEXT,
  fegru1_iden    NUMERIC,
  fegru1_nomb    TEXT,
  nc_cant        NUMERIC,
  anio           TEXT,
  estilo         TEXT,
  estado         TEXT,
  precio         TEXT,
  pvp            DOUBLE PRECISION,
  pvp1           DOUBLE PRECISION,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (iedefv_iden)
);

CREATE INDEX IF NOT EXISTS idx_raw_sales_detail_femi   ON bronze.raw_sales_detail (iefave_femi DESC);
CREATE INDEX IF NOT EXISTS idx_raw_sales_detail_prod   ON bronze.raw_sales_detail (ieprod_iden);
CREATE INDEX IF NOT EXISTS idx_raw_sales_detail_inv    ON bronze.raw_sales_detail (iefave_iden);

CREATE TABLE IF NOT EXISTS bronze.raw_credit_notes (
  iencrv_deud    NUMERIC,
  iencrv_favo    NUMERIC,
  ceautv_iden    NUMERIC,
  iencrv_iden    NUMERIC,
  feclie_iden    NUMERIC,
  fesucu_cods    NUMERIC,
  feclie_nomc    TEXT,
  feclie_codc    TEXT,
  feclie_trib    TEXT,
  fegru1_iden    NUMERIC,
  feclie_apec    TEXT,
  feempl_code    NUMERIC,
  ceautv_esta    TEXT,
  iencrv_femi    TIMESTAMPTZ,
  nsub5          DOUBLE PRECISION,
  nsub8          DOUBLE PRECISION,
  nsub12         DOUBLE PRECISION,
  nsub15         DOUBLE PRECISION,
  iencrv_civa    DOUBLE PRECISION,
  iencrv_siva    DOUBLE PRECISION,
  iencrv_dsct    DOUBLE PRECISION,
  iencrv_viva    DOUBLE PRECISION,
  iencrv_tota    DOUBLE PRECISION,
  iencrv_esta    TEXT,
  fesucu_noms    TEXT,
  iencrv_ser3    NUMERIC,
  ceautv_ser1    TEXT,
  ceautv_ser2    TEXT,
  iefave_iden    NUMERIC,
  iefave_ser3    NUMERIC,
  fegru1_nomb    TEXT,
  ser1_facv      TEXT,
  ser2_facv      TEXT,
  iefave_femi    TIMESTAMPTZ,
  iefave_civa    DOUBLE PRECISION,
  vsub5          DOUBLE PRECISION,
  vsub8          DOUBLE PRECISION,
  vsub12         DOUBLE PRECISION,
  vsub15         DOUBLE PRECISION,
  iefave_siva    DOUBLE PRECISION,
  iefave_dsct    DOUBLE PRECISION,
  iefave_viva    DOUBLE PRECISION,
  iefave_tota    DOUBLE PRECISION,
  iefave_fina    TEXT,
  rt_i           DOUBLE PRECISION,
  rt_r           DOUBLE PRECISION,
  ceautv_trib    TEXT,
  iefave_esta    TEXT,
  ceautv_trib_fac TEXT,
  ingestion_run_id  TEXT        NOT NULL,
  source_system     TEXT        NOT NULL DEFAULT 'on_prem_sql_server',
  source_object     TEXT        NOT NULL,
  extracted_at      TIMESTAMPTZ NOT NULL,
  source_row_hash   TEXT        NOT NULL,
  PRIMARY KEY (iencrv_iden)
);

CREATE INDEX IF NOT EXISTS idx_raw_credit_notes_femi ON bronze.raw_credit_notes (iencrv_femi DESC);
