# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - campomaqfront

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      - name: npm install, build, and test
        working-directory: apps/frontend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip apps/frontend/out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Clear old build folder
        run: rm -rf apps/frontend/out/*

      - name: Create target directory
        run: mkdir -p apps/frontend

      - name: Unzip artifact
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9D5AAAD987544514B3BF2E27E06DBEDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4C8EE3A6F704174806ACBA5CB5CA288 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_14251BFD72E64483881A54B4175FD57C }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'campomaqfront'
          slot-name: 'Production'
          package: ./apps/frontend/out
          startup-command: 'npm install -g serve && serve ./apps/frontend/out -l $PORT'
          